version: '3'

services:
  mysql:
    container_name: mysqlcontainer2
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  spring-boot-app:
    container_name: spring-container2
    image: spring-boot-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcontainer1:3306/docker 
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  react-app:
    container_name: react-container
    image: react_docker:dev
    ports:
      - "4000:3000"
    depends_on:
      - spring-boot-app
    environment:
      REACT_APP_API_URL: http://spring-container1:8080