version: '3'

services:
  mysql:
    container_name: mysqlcontainer1
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

  spring-boot-app:
    container_name: spring-container1
    image: spring-docker:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcontainer1:3306/docker 
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234 

  react-app:
    container_name: react-container
    image: react-docker1:dev
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app
    environment:
      REACT_APP_API_URL: http://spring-container1:8080